use gpui_kit::{App, KeyBinding, actions};

actions!(
    zenkai,
    [
        NewWorkbook,
        Open,
        Save,
        SaveAs,
        Quit,
        Undo,
        Redo,
        Copy,
        Cut,
        Paste,
        ToggleBold,
        ToggleItalic,
        ToggleUnderline,
        ToggleStrikethrough,
        GrowFont,
        ShrinkFont,
        AlignLeft,
        AlignCenter,
        AlignRight,
        FormatGeneral,
        FormatNumber,
        FormatCurrency,
        FormatPercent,
        FormatDate,
        ZoomIn,
        ZoomOut,
        ZoomReset,
        InterfaceLarger,
        InterfaceSmaller,
        InterfaceReset,
        ToggleReduceMotion,
        NoFill,
        AutomaticFontColor,
        NextSheet,
        PreviousSheet,
        NewSheet,
        ToggleTheme,
        ToggleDiagnostics,
        InsertChart,
        ChartColumn,
        ChartLine,
        ChartPie,
        ExportChartSvg,
        CopyChartMermaid,
        CloseChart,
        Find,
        CloseFind,
        TogglePalette,
        ClosePalette,
        RenameSheet,
        CloseRename,
        DeleteSheet,
        MoveSheetLeft,
        MoveSheetRight,
        GoTo,
        ConfirmCsvImport,
        CancelCsvImport,
        InsertRows,
        DeleteRows,
        InsertColumns,
        DeleteColumns,
        FreezePanes,
        FillDown,
        FillRight,
        AutoSum,
        InsertDate,
        InsertTime,
        CloseGoTo,
    ]
);

const CONTEXT: Option<&str> = Some("Workspace");

pub fn bind_keys(cx: &mut App) {
    cx.bind_keys([
        KeyBinding::new("ctrl-n", NewWorkbook, CONTEXT),
        KeyBinding::new("ctrl-o", Open, CONTEXT),
        KeyBinding::new("ctrl-s", Save, CONTEXT),
        KeyBinding::new("f12", SaveAs, CONTEXT),
        KeyBinding::new("ctrl-shift-s", SaveAs, CONTEXT),
        KeyBinding::new("alt-f4", Quit, CONTEXT),
        KeyBinding::new("ctrl-z", Undo, CONTEXT),
        KeyBinding::new("ctrl-y", Redo, CONTEXT),
        KeyBinding::new("ctrl-c", Copy, CONTEXT),
        KeyBinding::new("ctrl-x", Cut, CONTEXT),
        KeyBinding::new("ctrl-v", Paste, CONTEXT),
        KeyBinding::new("ctrl-b", ToggleBold, CONTEXT),
        KeyBinding::new("ctrl-i", ToggleItalic, CONTEXT),
        KeyBinding::new("ctrl-u", ToggleUnderline, CONTEXT),
        KeyBinding::new("ctrl-5", ToggleStrikethrough, CONTEXT),
        KeyBinding::new("ctrl-shift->", GrowFont, CONTEXT),
        KeyBinding::new("ctrl-shift-<", ShrinkFont, CONTEXT),
        KeyBinding::new("ctrl-shift-~", FormatGeneral, CONTEXT),
        KeyBinding::new("ctrl-shift-!", FormatNumber, CONTEXT),
        KeyBinding::new("ctrl-shift-$", FormatCurrency, CONTEXT),
        KeyBinding::new("ctrl-shift-%", FormatPercent, CONTEXT),
        KeyBinding::new("ctrl-shift-#", FormatDate, CONTEXT),
        KeyBinding::new("ctrl-=", ZoomIn, CONTEXT),
        KeyBinding::new("ctrl-+", ZoomIn, CONTEXT),
        KeyBinding::new("ctrl--", ZoomOut, CONTEXT),
        KeyBinding::new("ctrl-0", ZoomReset, CONTEXT),
        KeyBinding::new("ctrl-alt-=", InterfaceLarger, CONTEXT),
        KeyBinding::new("ctrl-alt--", InterfaceSmaller, CONTEXT),
        KeyBinding::new("ctrl-alt-0", InterfaceReset, CONTEXT),
        KeyBinding::new("ctrl-alt-m", ToggleReduceMotion, CONTEXT),
        KeyBinding::new("ctrl-pagedown", NextSheet, CONTEXT),
        KeyBinding::new("ctrl-pageup", PreviousSheet, CONTEXT),
        KeyBinding::new("shift-f11", NewSheet, CONTEXT),
        KeyBinding::new("ctrl-shift-d", ToggleDiagnostics, CONTEXT),
        KeyBinding::new("alt-f1", InsertChart, CONTEXT),
        KeyBinding::new("ctrl-f", Find, CONTEXT),
        KeyBinding::new("ctrl-shift-p", TogglePalette, CONTEXT),
        KeyBinding::new("escape", CloseRename, Some("RenameBar")),
        KeyBinding::new("ctrl-g", GoTo, CONTEXT),
        KeyBinding::new("enter", ConfirmCsvImport, Some("CsvPreview")),
        KeyBinding::new("escape", CancelCsvImport, Some("CsvPreview")),
        KeyBinding::new("f5", GoTo, CONTEXT),
        KeyBinding::new("ctrl-d", FillDown, CONTEXT),
        KeyBinding::new("ctrl-r", FillRight, CONTEXT),
        KeyBinding::new("alt-=", AutoSum, CONTEXT),
        KeyBinding::new("ctrl-;", InsertDate, CONTEXT),
        KeyBinding::new("ctrl-shift-;", InsertTime, CONTEXT),
        KeyBinding::new("ctrl-:", InsertTime, CONTEXT),
        KeyBinding::new("escape", CloseGoTo, Some("NameBox")),
        KeyBinding::new("escape", CloseFind, Some("FindBar")),
    ]);
}
