use gpui_kit::{App, KeyBinding, actions};

actions!(
    zenkai,
    [
        NewWorkbook,
        Open,
        Save,
        SaveAs,
        Quit,
        Undo,
        Redo,
        Copy,
        Cut,
        Paste,
        PasteValues,
        ToggleBold,
        ToggleItalic,
        ToggleUnderline,
        ToggleStrikethrough,
        GrowFont,
        ShrinkFont,
        AlignLeft,
        AlignCenter,
        AlignRight,
        FormatGeneral,
        FormatNumber,
        FormatCurrency,
        FormatPercent,
        FormatDate,
        ZoomIn,
        ZoomOut,
        ZoomReset,
        InterfaceLarger,
        InterfaceSmaller,
        InterfaceReset,
        ToggleReduceMotion,
        NoFill,
        ClearFormats,
        ClearAll,
        OpenRecent1,
        OpenRecent2,
        OpenRecent3,
        OpenRecent4,
        OpenRecent5,
        FormatCells,
        ApplyNumberFormat,
        CloseFormatDialog,
        ToggleFormulas,
        HideRows,
        HideColumns,
        UnhideRows,
        UnhideColumns,
        ToggleWrapText,
        IncreaseDecimal,
        DecreaseDecimal,
        SortAscending,
        SelectCurrentRegion,
        FreezeTopRow,
        FreezeFirstColumn,
        SortDescending,
        BordersAll,
        BordersOutside,
        BorderBottom,
        BordersNone,
        AutomaticFontColor,
        NextSheet,
        PreviousSheet,
        NewSheet,
        ToggleTheme,
        ToggleDiagnostics,
        InsertChart,
        ChartColumn,
        ChartLine,
        ChartPie,
        ExportChartSvg,
        CopyChartMermaid,
        CloseChart,
        Find,
        Replace,
        CloseFind,
        CancelFormulaBar,
        TogglePalette,
        ClosePalette,
        RenameSheet,
        CloseRename,
        DeleteSheet,
        DuplicateSheet,
        MoveSheetLeft,
        MoveSheetRight,
        GoTo,
        ConfirmCsvImport,
        CancelCsvImport,
        InsertRows,
        DeleteRows,
        InsertColumns,
        DeleteColumns,
        FreezePanes,
        FillDown,
        FillRight,
        AutoSum,
        InsertDate,
        InsertTime,
        CloseGoTo,
        NextDocument,
        PreviousDocument,
        CloseDocument,
        ReopenClosedDocument,
        ToggleSidebar,
        FocusSidebar,
        NewSpace,
        RenameSpace,
        DeleteSpace,
        MoveToPreviousSpace,
        MoveToNextSpace,
        SidebarUp,
        SidebarDown,
        SidebarFirst,
        SidebarLast,
        SidebarCollapse,
        SidebarExpand,
        SidebarOpen,
        LeaveSidebar,
        CloseSpaceRename,
        SidebarDelete,
        SearchFiles,
        CycleSpaceColor,
        CustomizeSpace,
        ResetSpaceAppearance,
        CloseSpacePanel,
        DeleteFile,
        CloseSearch,
        OpenSettings,
        CloseSettings,
        DetectAgents,
        AddClaudeAgent,
        AddGeminiAgent,
        AddCodexAgent,
        PermissionReadOnly,
        PermissionAskBeforeWrite,
        PermissionAutomatic,
        ToggleExternalAgents,
        FocusNextControl,
        FocusPreviousControl,
        CycleDefaultAgent,
        SaveSecrets,
        ApplyHeldSettings,
        KeepCurrentSettings,
        AllowAgentChange,
        DenyAgentChange,
        ShowAgentChange,
        LetAgentsEdit,
        CopyClaudeCommand,
        GenerateData,
        ConfirmGenerate,
        CancelGenerate,
        SaveGenerateHeaders,
        AddGenerateColumn,
    ]
);

const CONTEXT: Option<&str> = Some("Workspace");

pub fn bind_keys(cx: &mut App) {
    cx.bind_keys([
        KeyBinding::new("ctrl-n", NewWorkbook, CONTEXT),
        KeyBinding::new("ctrl-o", Open, CONTEXT),
        KeyBinding::new("ctrl-s", Save, CONTEXT),
        KeyBinding::new("f12", SaveAs, CONTEXT),
        KeyBinding::new("ctrl-shift-s", SaveAs, CONTEXT),
        KeyBinding::new("alt-f4", Quit, CONTEXT),
        KeyBinding::new("ctrl-z", Undo, CONTEXT),
        KeyBinding::new("ctrl-y", Redo, CONTEXT),
        KeyBinding::new("ctrl-c", Copy, CONTEXT),
        KeyBinding::new("ctrl-x", Cut, CONTEXT),
        KeyBinding::new("ctrl-v", Paste, CONTEXT),
        KeyBinding::new("ctrl-shift-v", PasteValues, CONTEXT),
        KeyBinding::new("ctrl-b", ToggleBold, CONTEXT),
        KeyBinding::new("ctrl-i", ToggleItalic, CONTEXT),
        KeyBinding::new("ctrl-u", ToggleUnderline, CONTEXT),
        KeyBinding::new("ctrl-5", ToggleStrikethrough, CONTEXT),
        KeyBinding::new("ctrl-1", FormatCells, CONTEXT),
        KeyBinding::new("enter", ApplyNumberFormat, Some("FormatDialog")),
        KeyBinding::new("escape", CloseFormatDialog, Some("FormatDialog")),
        KeyBinding::new("ctrl-`", ToggleFormulas, CONTEXT),
        KeyBinding::new("ctrl-*", SelectCurrentRegion, CONTEXT),
        KeyBinding::new("ctrl-&", BordersOutside, CONTEXT),
        KeyBinding::new("ctrl-_", BordersNone, CONTEXT),
        KeyBinding::new("ctrl->", GrowFont, CONTEXT),
        KeyBinding::new("ctrl-<", ShrinkFont, CONTEXT),
        KeyBinding::new("ctrl-~", FormatGeneral, CONTEXT),
        KeyBinding::new("ctrl-!", FormatNumber, CONTEXT),
        KeyBinding::new("ctrl-$", FormatCurrency, CONTEXT),
        KeyBinding::new("ctrl-%", FormatPercent, CONTEXT),
        KeyBinding::new("ctrl-#", FormatDate, CONTEXT),
        KeyBinding::new("ctrl-=", ZoomIn, CONTEXT),
        KeyBinding::new("ctrl-+", ZoomIn, CONTEXT),
        KeyBinding::new("ctrl--", ZoomOut, CONTEXT),
        KeyBinding::new("ctrl-9", HideRows, CONTEXT),
        KeyBinding::new("ctrl-0", HideColumns, CONTEXT),
        KeyBinding::new("ctrl-(", UnhideRows, CONTEXT),
        KeyBinding::new("ctrl-)", UnhideColumns, CONTEXT),
        KeyBinding::new("ctrl-alt-=", InterfaceLarger, CONTEXT),
        KeyBinding::new("ctrl-alt--", InterfaceSmaller, CONTEXT),
        KeyBinding::new("ctrl-alt-0", InterfaceReset, CONTEXT),
        KeyBinding::new("ctrl-alt-m", ToggleReduceMotion, CONTEXT),
        KeyBinding::new("ctrl-tab", NextDocument, CONTEXT),
        KeyBinding::new("ctrl-shift-tab", PreviousDocument, CONTEXT),
        KeyBinding::new("ctrl-w", CloseDocument, CONTEXT),
        KeyBinding::new("ctrl-shift-t", ReopenClosedDocument, CONTEXT),
        KeyBinding::new("ctrl-alt-b", ToggleSidebar, CONTEXT),
        KeyBinding::new("ctrl-e", SearchFiles, CONTEXT),
        KeyBinding::new("f6", FocusSidebar, CONTEXT),
        KeyBinding::new("ctrl-alt-r", RenameSpace, CONTEXT),
        KeyBinding::new("ctrl-alt-k", CycleSpaceColor, CONTEXT),
        KeyBinding::new("ctrl-alt-shift-k", CustomizeSpace, CONTEXT),
        KeyBinding::new("ctrl-alt-shift-r", ResetSpaceAppearance, CONTEXT),
        KeyBinding::new("escape", CloseSpacePanel, Some("SpacePanel")),
        KeyBinding::new("tab", FocusNextControl, Some("SpacePanel")),
        KeyBinding::new("shift-tab", FocusPreviousControl, Some("SpacePanel")),
        KeyBinding::new(
            "ctrl-shift-delete",
            DeleteFile,
            Some("Sidebar && !SpaceRename"),
        ),
        KeyBinding::new("ctrl-alt-shift-d", DeleteSpace, CONTEXT),
        KeyBinding::new("ctrl-alt-n", NewSpace, CONTEXT),
        KeyBinding::new("ctrl-alt-pageup", MoveToPreviousSpace, CONTEXT),
        KeyBinding::new("ctrl-alt-pagedown", MoveToNextSpace, CONTEXT),
        KeyBinding::new("up", SidebarUp, Some("Sidebar && !SpaceRename")),
        KeyBinding::new("down", SidebarDown, Some("Sidebar && !SpaceRename")),
        KeyBinding::new("home", SidebarFirst, Some("Sidebar && !SpaceRename")),
        KeyBinding::new("end", SidebarLast, Some("Sidebar && !SpaceRename")),
        KeyBinding::new("left", SidebarCollapse, Some("Sidebar && !SpaceRename")),
        KeyBinding::new("right", SidebarExpand, Some("Sidebar && !SpaceRename")),
        KeyBinding::new("enter", SidebarOpen, Some("Sidebar && !SpaceRename")),
        KeyBinding::new("escape", LeaveSidebar, Some("Sidebar && !SpaceRename")),
        KeyBinding::new("f2", RenameSpace, Some("Sidebar && !SpaceRename")),
        KeyBinding::new("delete", SidebarDelete, Some("Sidebar && !SpaceRename")),
        KeyBinding::new(
            "alt-up",
            MoveToPreviousSpace,
            Some("Sidebar && !SpaceRename"),
        ),
        KeyBinding::new("alt-down", MoveToNextSpace, Some("Sidebar && !SpaceRename")),
        KeyBinding::new("escape", CloseSpaceRename, Some("SpaceRename")),
        KeyBinding::new("ctrl-pagedown", NextSheet, CONTEXT),
        KeyBinding::new("ctrl-pageup", PreviousSheet, CONTEXT),
        KeyBinding::new("shift-f11", NewSheet, CONTEXT),
        KeyBinding::new("ctrl-shift-d", ToggleDiagnostics, CONTEXT),
        KeyBinding::new("alt-f1", InsertChart, CONTEXT),
        KeyBinding::new("ctrl-f", Find, CONTEXT),
        KeyBinding::new("ctrl-h", Replace, CONTEXT),
        KeyBinding::new("ctrl-shift-p", TogglePalette, CONTEXT),
        KeyBinding::new("escape", CloseRename, Some("RenameBar")),
        KeyBinding::new("ctrl-g", GoTo, CONTEXT),
        KeyBinding::new("enter", ConfirmCsvImport, Some("CsvPreview")),
        KeyBinding::new("escape", CancelCsvImport, Some("CsvPreview")),
        KeyBinding::new("f5", GoTo, CONTEXT),
        KeyBinding::new("ctrl-d", FillDown, CONTEXT),
        KeyBinding::new("ctrl-r", FillRight, CONTEXT),
        KeyBinding::new("alt-=", AutoSum, CONTEXT),
        KeyBinding::new("ctrl-;", InsertDate, CONTEXT),
        KeyBinding::new("ctrl-shift-;", InsertTime, CONTEXT),
        KeyBinding::new("ctrl-:", InsertTime, CONTEXT),
        KeyBinding::new("escape", CloseGoTo, Some("NameBox")),
        KeyBinding::new("escape", CloseFind, Some("FindBar")),
        KeyBinding::new("escape", CancelFormulaBar, Some("FormulaBar")),
        KeyBinding::new("escape", ClosePalette, Some("Palette")),
        KeyBinding::new("escape", CloseSearch, Some("SearchOverlay")),
        KeyBinding::new("ctrl-,", OpenSettings, CONTEXT),
        KeyBinding::new("escape", CloseSettings, Some("SettingsPage")),
        KeyBinding::new("f5", DetectAgents, Some("SettingsPage")),
        KeyBinding::new("alt-c", AddClaudeAgent, Some("SettingsPage")),
        KeyBinding::new("alt-g", AddGeminiAgent, Some("SettingsPage")),
        KeyBinding::new("alt-x", AddCodexAgent, Some("SettingsPage")),
        KeyBinding::new("alt-r", PermissionReadOnly, Some("SettingsPage")),
        KeyBinding::new("alt-a", PermissionAskBeforeWrite, Some("SettingsPage")),
        KeyBinding::new("alt-u", PermissionAutomatic, Some("SettingsPage")),
        KeyBinding::new("alt-e", ToggleExternalAgents, Some("SettingsPage")),
        KeyBinding::new("tab", FocusNextControl, Some("SettingsPage")),
        KeyBinding::new("shift-tab", FocusPreviousControl, Some("SettingsPage")),
        KeyBinding::new("alt-d", CycleDefaultAgent, Some("SettingsPage")),
        KeyBinding::new("alt-s", SaveSecrets, Some("SettingsPage")),
        KeyBinding::new("alt-m", CopyClaudeCommand, Some("SettingsPage")),
        KeyBinding::new("enter", KeepCurrentSettings, Some("HeldSettings")),
        KeyBinding::new("escape", KeepCurrentSettings, Some("HeldSettings")),
        KeyBinding::new("alt-a", ApplyHeldSettings, Some("HeldSettings")),
        KeyBinding::new("enter", DenyAgentChange, Some("AgentApproval")),
        KeyBinding::new("alt-y", AllowAgentChange, Some("AgentApproval")),
        KeyBinding::new("escape", DenyAgentChange, Some("AgentApproval")),
        KeyBinding::new("ctrl-shift-e", LetAgentsEdit, CONTEXT),
        KeyBinding::new("alt-a", ApplyHeldSettings, CONTEXT),
        KeyBinding::new("alt-y", AllowAgentChange, CONTEXT),
        KeyBinding::new("alt-w", ShowAgentChange, CONTEXT),
        KeyBinding::new("alt-n", DenyAgentChange, CONTEXT),
        KeyBinding::new("ctrl-alt-g", GenerateData, CONTEXT),
        KeyBinding::new("enter", ConfirmGenerate, Some("GenerateDialog > Input")),
        KeyBinding::new("escape", CancelGenerate, Some("GenerateDialog")),
        KeyBinding::new("alt-h", SaveGenerateHeaders, Some("GenerateDialog")),
        KeyBinding::new("alt-n", AddGenerateColumn, Some("GenerateDialog")),
        KeyBinding::new("tab", FocusNextControl, Some("GenerateDialog")),
        KeyBinding::new("shift-tab", FocusPreviousControl, Some("GenerateDialog")),
    ]);
}
