[package]
name = "zenkai-bench"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ironcalc = "=0.8.3"
logisheets-rs = "=1.16.1"
rust_xlsxwriter = "0.92"
rand = "0.9"
rand_chacha = "0.9"
anyhow = "1"
peak_alloc = "0.3"

[lints]
workspace = true
